const fs = require('fs');
const file = 'src/pages/TrackingPage.tsx';

let content = fs.readFileSync(file, 'utf8');

const replacements = [
  [/[\uFFFD\?]*Theo d[\s\S]{1,3}i don hang/g, 'Theo dõi đơn hàng'],
  [/[\uFFFD\?]*Theo d[\s\S]{1,3}i don/g, 'Theo dõi đơn'],
  [/[\uFFFD\?]*Chua c[\s\S]{1,3} don h[\s\S]{1,3}ng d\? theo d[\s\S]{1,3}i/g, 'Chưa có đơn hàng để theo dõi'],
  [/[\uFFFD\?]*\?t m[\s\S]{1,3}n xong b\?n s\? th\?y ti\?n tr[\s\S]{1,3}nh giao h[\s\S]{1,3}ng v[\s\S]{1,3} l\? tr[\s\S]{1,3}nh t[\s\S]{1,3}i x\? t\?i d[\s\S]{1,3}y\./g, 'Đặt món xong bạn sẽ thấy tiến trình giao hàng và lộ trình tài xế tại đây.'],
  [/[\uFFFD\?]*\?t m[\s\S]{1,3}n ngay/g, 'Đặt món ngay'],
  [/[\uFFFD\?]*ang t\?i don h[\s\S]{1,3}ng c[\s\S]{1,3}a b\?n\.\.\./g, 'Đang tải đơn hàng của bạn...'],
  [/[\uFFFD\?]*on h[\s\S]{1,3}ng c[\s\S]{1,3}a b\?n/g, 'Đơn hàng của bạn'],
  [/>\s*[\uFFFD\?]+on hang cua ban\s*</g, '>Đơn hàng của bạn<'],
  [/[\uFFFD\?]*Chua c[\s\S]{1,3} don h[\s\S]{1,3}ng n[\s\S]{1,3}o/g, 'Chưa có đơn hàng nào'],
  [/[\uFFFD\?]*\?t m[\s\S]{1,3}n d\? xem l\?ch s\? v[\s\S]{1,3} theo d[\s\S]{1,3}i giao h[\s\S]{1,3}ng t\?i d[\s\S]{1,3}y\./g, 'Đặt món để xem lịch sử và theo dõi giao hàng tại đây.'],
  [/[\uFFFD\?]*T[\s\S]{1,3}i x\? d[\s\S]{1,3} nh\?n don/g, 'Tài xế đã nhận đơn'],
  [/>\s*[\uFFFD\?]*hi\?u\s*</g, '>Đã hiểu<'],
  [/[\uFFFD\?]*d[\s\S]{1,3} nh\?n don v[\s\S]{1,3} dang di l\?y m[\s\S]{1,3}n cho b\?n\./g, 'đã nhận đơn và đang đi lấy món cho bạn.'],
  [/[\uFFFD\?]*T[\s\S]{1,3}i x\? dang giao d\?n b\?n/g, 'Tài xế đang giao đến bạn'],
  [/[\uFFFD\?]*d[\s\S]{1,3} l\?y m[\s\S]{1,3}n xong v[\s\S]{1,3} dang chu\?n b\? giao d\?n cho b\?n\./g, 'đã lấy món xong và đang chuẩn bị giao đến cho bạn.'],
  [/[\uFFFD\?]*Vui l[\s\S]{1,3}ng chu\?n b\? ti\?n m\?t/g, 'Vui lòng chuẩn bị tiền mặt'],
  [/>\s*[\uFFFD\?]*giao h[\s\S]{1,3}ng th[\s\S]{1,3}nh c[\s\S]{1,3}ng\s*</g, '>Đã giao hàng thành công<'],
  [/[\uFFFD\?]*d[\s\S]{1,3} giao don h[\s\S]{1,3}ng d\?n cho b\?n th[\s\S]{1,3}nh c[\s\S]{1,3}ng\./g, 'đã giao đơn hàng đến cho bạn thành công.'],
  [/[\uFFFD\?]*T\?ng gi[\s\S]{1,3} tr\? don/g, 'Tổng giá trị đơn'],
  [/[\uFFFD\?]*C\?m on b\?n d[\s\S]{1,3} s\? d\?ng d\?ch v\?!/g, 'Cảm ơn bạn đã sử dụng dịch vụ!'],
  [/[\uFFFD\?]*Theo d[\s\S]{1,3}i tr\?c ti\?p/g, 'Theo dõi trực tiếp'],
  [/[\uFFFD\?]* don da d[\s\S]{1,3}t /g, ' đơn đã đặt '],
  [/[\uFFFD\?]* don dang x\? l[\s\S]{1,3}/g, ' đơn đang xử lý'],
  [/[\uFFFD\?]*ang t\?i th[\s\S]{1,3}ng tin don h[\s\S]{1,3}ng\.\.\./g, 'Đang tải thông tin đơn hàng...'],
  [/>\s*[\uFFFD\?]*ang t\?i\s*</g, '>Đang tải<'],
  [/[\uFFFD\?]*Ch\? t[\s\S]{1,3}i x\?/g, 'Chờ tài xế'],
  [/[\uFFFD\?]*Nh[\s\S]{1,3} h[\s\S]{1,3}ng/g, 'Nhà hàng'],
  [/[\uFFFD\?]*ang c\?p nh\?t/g, 'Đang cập nhật'],
  [/>\s*[\uFFFD\?]*T[\s\S]{1,3}i x\?\s*</g, '>Tài xế<'],
  [/[\uFFFD\?]*Chua c[\s\S]{1,3} t[\s\S]{1,3}i x\?/g, 'Chưa có tài xế'],
  [/[\uFFFD\?]*S[\s\S]{1,3}T kh[\s\S]{1,3}ch/g, 'SĐT khách'],
  [/[\uFFFD\?]*Bi\?n s\?/g, 'Biển số'],
  [/[\uFFFD\?]*Ti\?n c\?n thu/g, 'Tiền cần thu'],
  [/[\uFFFD\?]*Qu[\s\S]{1,3}ng du\?ng/g, 'Quãng đường'],
  [/[\uFFFD\?]*Chua c[\s\S]{1,3} l\? tr[\s\S]{1,3}nh/g, 'Chưa có lộ trình'],
  [/[\uFFFD\?]*M[\s\S]{1,3}n d[\s\S]{1,3} d\?t/g, 'Món đã đặt'],
  [/[\uFFFD\?]*Chua \?nh/g, 'Chưa ảnh'],
  [/[\uFFFD\?]*M[\s\S]{1,3}n #/g, 'Món #'],
  [/[\uFFFD\?]*T\?m t[\s\S]{1,3}nh/g, 'Tạm tính'],
  [/[\uFFFD\?]*Ph[\s\S]{1,3} giao h[\s\S]{1,3}ng/g, 'Phí giao hàng'],
  [/[\uFFFD\?]*Gi\?m gi[\s\S]{1,3}/g, 'Giảm giá'],
  [/[\uFFFD\?]*Thu\?/g, 'Thuế'],
  [/[\uFFFD\?]*T\?ng thanh to[\s\S]{1,3}n/g, 'Tổng thanh toán'],
  [/[\uFFFD\?]*\?t th[\s\S]{1,3}m m[\s\S]{1,3}n/g, 'Đặt thêm món'],
  [/[\uFFFD\?]*nh gi[\s\S]{1,3} nh[\s\S]{1,3} h[\s\S]{1,3}ng/g, 'Đánh giá nhà hàng'],
  [/[\uFFFD\?]*on da ho[\s\S]{1,3}n th[\s\S]{1,3}nh, b\?n c[\s\S]{1,3} th\? ch\?m sao cho tr\?i nghi\?m v\?a r\?i\./g, 'Đơn đã hoàn thành, bạn có thể chấm sao cho trải nghiệm vừa rồi.'],
  [/[\uFFFD\?]*Nh\?n x[\s\S]{1,3}t ng\?n v\? nh[\s\S]{1,3} h[\s\S]{1,3}ng\.\.\./g, 'Nhận xét ngắn về nhà hàng...'],
  [/[\uFFFD\?]*ang g\?i\.\.\./g, 'Đang gửi...'],
  [/[\uFFFD\?]*G\?i d[\s\S]{1,3}nh gi[\s\S]{1,3}/g, 'Gửi đánh giá'],
  [/[\uFFFD\?]*on da d\?t/g, 'Đơn đã đặt'],
  [/[\uFFFD\?]*Tai l\?i/g, 'Tải lại'],
  [/[\uFFFD\?]*T\?t c\?/g, 'Tất cả'],
  [/[\uFFFD\?]*Dang giao/g, 'Đang giao'],
  [/[\uFFFD\?]*Kh[\s\S]{1,3}ng c[\s\S]{1,3} don ph[\s\S]{1,3} h\?p b\? l\?c\./g, 'Không có đơn phù hợp bộ lọc.'],
  [/>\s*[\uFFFD\?]*Tru\?c\s*</g, '>Trước<'],
  [/>\s*[\uFFFD\?]*Ti\?p\s*</g, '>Tiếp<'],
  [/>\s*[\uFFFD\?]*Dat don\s*</g, '>Đặt đơn<'],
  [/[\uFFFD\?]*T[\s\S]{1,3}i x\? nhan/g, 'Tài xế nhận'],
  [/>\s*[\uFFFD\?]*Lay m[\s\S]{1,3}n\s*</g, '>Lấy món<'],
  [/>\s*[\uFFFD\?]*ang xem\s*</g, '>Đang xem<'],
  [/[\uFFFD\?]*Xem chi ti\?t/g, 'Xem chi tiết'],
  [/[\uFFFD\?]*m[\s\S]{1,3}n kh[\s\S]{1,3}c/g, 'món khác'],
  [/>\s*[\uFFFD\?]*Theo d[\s\S]{1,3}i\s*</g, '>Theo dõi<'],
  [/[\uFFFD\?]*Kh[\s\S]{1,3}ng th\? h\?y don h[\s\S]{1,3}ng/g, 'Không thể hủy đơn hàng'],
  [/[\uFFFD\?]*Kh[\s\S]{1,3}ng th\? t\?i danh s[\s\S]{1,3}ch don h[\s\S]{1,3}ng/g, 'Không thể tải danh sách đơn hàng'],
  [/[\uFFFD\?]*Kh[\s\S]{1,3}ng th\? t\?i tracking/g, 'Không thể tải tracking'],
  [/[\uFFFD\?]* g\?i d[\s\S]{1,3}nh gi[\s\S]{1,3} nh[\s\S]{1,3} h[\s\S]{1,3}ng\. C\?m on b\?n!/g, ' đã gửi đánh giá nhà hàng. Cảm ơn bạn!'],
  [/[\uFFFD\?]*Kh[\s\S]{1,3}ng th\? g\?i d[\s\S]{1,3}nh gi[\s\S]{1,3}/g, 'Không thể gửi đánh giá'],
  [/[\uFFFD\?]*ang t\?i\.\.\./g, 'Đang tải...'],
  [/[\uFFFD\?]*on da dat/g, 'Đơn đã đặt'],
  [/[\uFFFD\?]*dang xu ly/g, 'đang xử lý'],
];

for (const [regex, replacement] of replacements) {
  content = content.replace(regex, replacement);
}

fs.writeFileSync(file, content, 'utf8');
console.log('Successfully fixed TrackingPage.tsx with explicit regex 2');
