const fs = require('fs');
const file = 'src/pages/TrackingPage.tsx';
let content = fs.readFileSync(file, 'utf8');

const replacements = [
  ['Theo d\uFFFD\uFFFD\uFFFDi don hang', 'Theo dõi đơn hàng'],
  ['Theo d\uFFFD\uFFFD\uFFFDi don', 'Theo dõi đơn'],
  ['Chua c\uFFFD\uFFFD\uFFFDo don h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng d?', 'Chưa có đơn hàng để'],
  ['Theo d\uFFFD\uFFFD\uFFFDi tr?c ti?p', 'Theo dõi trực tiếp'],
  ['Chua c\uFFFD\uFFFD\uFFFDo don h\uFFFD\uFFFD\uFFFDng n\uFFFD\uFFFD\uFFFDo', 'Chưa có đơn hàng nào'],
  ['\uFFFD\uFFFD\uFFFD?t m\uFFFD\uFFFD\uFFFDo\uFFFD\uFFFD\uFFFDn ngay', 'Đặt món ngay'],
  ['\uFFFD\uFFFD\uFFFDang t?i don h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng c\uFFFD\uFFFD\uFFFDu\uFFFD\uFFFD\uFFFDa b\uFFFD\uFFFD\uFFFDn...', 'Đang tải đơn hàng của bạn...'],
  ['\uFFFD\uFFFD\uFFFDon h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng c\uFFFD\uFFFD\uFFFDu\uFFFD\uFFFD\uFFFDa b\uFFFD\uFFFD\uFFFDn', 'Đơn hàng của bạn'],
  ['T\uFFFD\uFFFD\uFFFDi x? nh\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDn', 'Tài xế nhận'],
  ['T\uFFFD\uFFFD\uFFFDi x?', 'Tài xế'],
  ['\uFFFD\uFFFD\uFFFDa hi?u', 'Đã hiểu'],
  ['Ch\uFFFD\uFFFD\uFFFDo t\uFFFD\uFFFD\uFFFDi x?', 'Chờ tài xế'],
  ['Nh\uFFFD\uFFFD\uFFFDa h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng', 'Nhà hàng'],
  ['\uFFFD\uFFFD\uFFFDang c?p nh?t', 'Đang cập nhật'],
  ['Chua c\uFFFD\uFFFD\uFFFDo t\uFFFD\uFFFD\uFFFDi x?', 'Chưa có tài xế'],
  ['S\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDT kh\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDch', 'SĐT khách'],
  ['Bi?n s?', 'Biển số'],
  ['Ti?n c?n thu', 'Tiền cần thu'],
  ['Qu\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng du?\uFFFD\uFFFD\uFFFDng', 'Quãng đường'],
  ['Chua c\uFFFD\uFFFD\uFFFDo l? tr\uFFFD\uFFFD\uFFFDi\uFFFD\uFFFD\uFFFDnh', 'Chưa có lộ trình'],
  ['M\uFFFD\uFFFD\uFFFDo\uFFFD\uFFFD\uFFFDn d\uFFFD\uFFFD\uFFFDa d?t', 'Món đã đặt'],
  ['Chua ?nh', 'Chưa ảnh'],
  ['M\uFFFD\uFFFD\uFFFDo\uFFFD\uFFFD\uFFFDn #', 'Món #'],
  ['T?m t\uFFFD\uFFFD\uFFFDi\uFFFD\uFFFD\uFFFDnh', 'Tạm tính'],
  ['Ph\uFFFD\uFFFD\uFFFDi giao h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng', 'Phí giao hàng'],
  ['Gi?m gi\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFD', 'Giảm giá'],
  ['Thu?', 'Thuế'],
  ['T?ng thanh to\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDn', 'Tổng thanh toán'],
  ['\uFFFD\uFFFD\uFFFD?t th\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDm m\uFFFD\uFFFD\uFFFDo\uFFFD\uFFFD\uFFFDn', 'Đặt thêm món'],
  ['\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDnh gi\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFD nh\uFFFD\uFFFD\uFFFDa h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng', 'Đánh giá nhà hàng'],
  ['\uFFFD\uFFFD\uFFFDon d\uFFFD\uFFFD\uFFFDa ho\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDn th\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDnh, b?n c\uFFFD\uFFFD\uFFFDo th? ch?m sao cho tr?i nghi?m v?a r?i.', 'Đơn đã hoàn thành, bạn có thể chấm sao cho trải nghiệm vừa rồi.'],
  ['Nh?n x\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDt ng?n v? nh\uFFFD\uFFFD\uFFFDa h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng...', 'Nhận xét ngắn về nhà hàng...'],
  ['\uFFFD\uFFFD\uFFFDang g?i...', 'Đang gửi...'],
  ['G?i d\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDnh gi\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFD', 'Gửi đánh giá'],
  ['\uFFFD\uFFFD\uFFFDon d\uFFFD\uFFFD\uFFFDa d?t', 'Đơn đã đặt'],
  [' dang x? l\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD', ' đang xử lý'],
  ['T\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDi l?i', 'Tải lại'],
  ['T?t c?', 'Tất cả'],
  ['\uFFFD\uFFFD\uFFFDang giao', 'Đang giao'],
  ['Kh\uFFFD\uFFFD\uFFFDo\uFFFD\uFFFD\uFFFDng c\uFFFD\uFFFD\uFFFDo don ph\uFFFD\uFFFD\uFFFDu\uFFFD\uFFFD\uFFFD h?p b? l?c.', 'Không có đơn phù hợp bộ lọc.'],
  ['Tru?c', 'Trước'],
  ['Ti?p', 'Tiếp'],
  ['Kh\uFFFD\uFFFD\uFFFDo\uFFFD\uFFFD\uFFFDng th? h?y don h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng', 'Không thể hủy đơn hàng'],
  ['Kh\uFFFD\uFFFD\uFFFDo\uFFFD\uFFFD\uFFFDng th? t?i danh s\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDch don h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng', 'Không thể tải danh sách đơn hàng'],
  ['Kh\uFFFD\uFFFD\uFFFDo\uFFFD\uFFFD\uFFFDng th? t?i tracking', 'Không thể tải tracking'],
  [' g?i d\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDnh gi\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFD nh\uFFFD\uFFFD\uFFFDa h\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFDng. C?m on b?n!', ' đã gửi đánh giá nhà hàng. Cảm ơn bạn!'],
  ['Kh\uFFFD\uFFFD\uFFFDo\uFFFD\uFFFD\uFFFDng th? g?i d\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFDnh gi\uFFFD\uFFFD\uFFFDa\uFFFD\uFFFD\uFFFD', 'Không thể gửi đánh giá'],
  ['Theo d\uFFFD\uFFFD\uFFFDi', 'Theo dõi'],
  ['\uFFFD\uFFFD\uFFFDang xem', 'Đang xem'],
  ['Xem chi ti?t', 'Xem chi tiết']
];

let replaced = content;
// Since the file has literal '?' and '\uFFFD', let's use a regex replace for the known patterns.
// It's much easier to just replace any \uFFFD+ and \?+ mixed with the ASCII letters with the correct word.

const robustDict = {
  'Theo d.*i don hang': 'Theo dõi đơn hàng',
  'Theo d.*i don': 'Theo dõi đơn',
  'Chua c.* don h.*g d\\? theo d.*i': 'Chưa có đơn hàng để theo dõi',
  '\\?t m.*n xong b\\?n s\\? th\\?y ti\\?n tr.*nh giao h.*g v.* l\\? tr.*nh t.*i x\\? t\\?i d.*y\\.': 'Đặt món xong bạn sẽ thấy tiến trình giao hàng và lộ trình tài xế tại đây.',
  '\\?t m.*n ngay': 'Đặt món ngay',
  'ang t\\?i don h.*g c.*a b\\?n...': 'Đang tải đơn hàng của bạn...',
  'on h.*g c.*a b\\?n': 'Đơn hàng của bạn',
  'Chua c.* don h.*g n.*o': 'Chưa có đơn hàng nào',
  '\\?t m.*n d\\? xem l\\?ch s\\? v.* theo d.*i giao h.*g t\\?i d.*y\\.': 'Đặt món để xem lịch sử và theo dõi giao hàng tại đây.',
  'T.*i x\\? d.* nh\\?n don': 'Tài xế đã nhận đơn',
  ' hi\\?u': ' đã hiểu',
  'd.* nh\\?n don v.* dang di l\\?y m.*n cho b\\?n\\.': 'đã nhận đơn và đang đi lấy món cho bạn.',
  'T.*i x\\? dang giao d\\?n b\\?n': 'Tài xế đang giao đến bạn',
  'd.* l\\?y m.*n xong v.* dang chu\\?n b\\? giao d\\?n cho b\\?n\\.': 'đã lấy món xong và đang chuẩn bị giao đến cho bạn.',
  'Vui l.*ng chu\\?n b\\? ti\\?n m\\?t': 'Vui lòng chuẩn bị tiền mặt',
  ' giao h.*g th.*nh c.*g': ' giao hàng thành công',
  'd.* giao don h.*g d\\?n cho b\\?n th.*nh c.*g\\.': 'đã giao đơn hàng đến cho bạn thành công.',
  'T\\?ng gi.* tr\\? don': 'Tổng giá trị đơn',
  'C\\?m on b\\?n d.* s\\? d\\?ng d\\?ch v\\?!': 'Cảm ơn bạn đã sử dụng dịch vụ!',
  'Theo d.*i tr\\?c ti\\?p': 'Theo dõi trực tiếp',
  ' don da d.*t': ' đơn đã đặt',
  ' don dang x\\? l.*': ' đơn đang xử lý',
  'ang t\\?i th.*ng tin don h.*g...': 'Đang tải thông tin đơn hàng...',
  'ang t\\?i': 'Đang tải',
  'Ch\\? t.*i x\\?': 'Chờ tài xế',
  'Nh.* h.*ng': 'Nhà hàng',
  'ang c\\?p nh\\?t': 'Đang cập nhật',
  'T.*i x\\?': 'Tài xế',
  'Chua c.* t.*i x\\?': 'Chưa có tài xế',
  'S.*T kh.*ch': 'SĐT khách',
  'Bi\\?n s\\?': 'Biển số',
  'Ti\\?n c\\?n thu': 'Tiền cần thu',
  'Qu.*ng du\\?ng': 'Quãng đường',
  'Chua c.* l\\? tr.*nh': 'Chưa có lộ trình',
  'M.*n d.* d\\?t': 'Món đã đặt',
  'Chua \\?nh': 'Chưa ảnh',
  'M.*n #': 'Món #',
  'T\\?m t.*nh': 'Tạm tính',
  'Ph.* giao h.*g': 'Phí giao hàng',
  'Gi\\?m gi.*': 'Giảm giá',
  'Thu\\?': 'Thuế',
  'T\\?ng thanh to.*n': 'Tổng thanh toán',
  '\\?t th.*m m.*n': 'Đặt thêm món',
  'nh gi.* nh.* h.*g': 'Đánh giá nhà hàng',
  'on da ho.*n th.*nh, b\\?n c.* th\\? ch\\?m sao cho tr\\?i nghi\\?m v\\?a r\\?i\\.': 'Đơn đã hoàn thành, bạn có thể chấm sao cho trải nghiệm vừa rồi.',
  'Nh\\?n x.*t ng\\?n v\\? nh.* h.*ng...': 'Nhận xét ngắn về nhà hàng...',
  'ang g\\?i...': 'Đang gửi...',
  'G\\?i d.*nh gi.*': 'Gửi đánh giá',
  'on da d\\?t': 'Đơn đã đặt',
  'Tai l\\?i': 'Tải lại',
  'T\\?t c\\?': 'Tất cả',
  'Dang giao': 'Đang giao',
  'Kh.*ng c.* don ph.* h\\?p b\\? l\\?c\\.': 'Không có đơn phù hợp bộ lọc.',
  'Tru\\?c': 'Trước',
  'Ti\\?p': 'Tiếp',
  'Dat don': 'Đặt đơn',
  'T.*i x\\? nhan': 'Tài xế nhận',
  'Lay m.*n': 'Lấy món',
  'ang xem': 'Đang xem',
  'Xem chi ti\\?t': 'Xem chi tiết',
  'm.*n kh.*c': 'món khác',
  'Theo d.*i': 'Theo dõi',
  'Kh.*ng th\\? h\\?y don h.*g': 'Không thể hủy đơn hàng',
  'Kh.*ng th\\? t\\?i danh s.*ch don h.*g': 'Không thể tải danh sách đơn hàng',
  'Kh.*ng th\\? t\\?i tracking': 'Không thể tải tracking',
  ' g\\?i d.*nh gi.* nh.* h.*g\\. C\\?m on b\\?n!': ' đã gửi đánh giá nhà hàng. Cảm ơn bạn!',
  'Kh.*ng th\\? g\\?i d.*nh gi.*': 'Không thể gửi đánh giá'
};

for (const [key, value] of Object.entries(robustDict)) {
  const regex = new RegExp(key.replace(/\./g, '\\.').replace(/\.\*/g, '[\\uFFFD\\?a-zA-Z]*'), 'g');
  replaced = replaced.replace(regex, value);
}

fs.writeFileSync(file, replaced, 'utf8');
console.log('Fixed TrackingPage.tsx with regex');
